FROM rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1

RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && apt-get install --no-install-recommends -y libdbus-1-dev:arm64 \
       pkg-config libudev-dev:arm64 libglib2.0-dev:arm64
